library(ggplot2)
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
png(file = "plot5.png")
sccsub <- data.frame(subset(SCC, grepl("mobile", EI.Sector, ignore.case = TRUE)))
neisub <- data.frame(subset(NEI, fips == "24510"))
mydata <- merge(sccsub, neisub, by = "SCC", all = FALSE)
g <- ggplot(mydata, aes(Emissions, year))
p <- g + geom_point()
print(p)
