library(ggplot2)
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- data.frame(readRDS("Source_Classification_Code.rds"))
png(file = "plot4.png")
sccsub <- subset(SCC, grepl("Coal", EI.Sector, ignore.case = TRUE))
mydata <- merge(NEI, sccsub, by = "SCC", all = FALSE)
g <- ggplot(mydata, aes(Emissions, year))
p <- g + geom_point()
print(p)
